/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Seguridad.Informar;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import Modulo_Seguridad.Pantalla_Seguridad;

/**
 *
 * @author PC
 */
public class Mostrar_Informe extends javax.swing.JFrame {
    Crear_Informe_Codigo cIc = new Crear_Informe_Codigo();
    DefaultListModel modelo = new DefaultListModel();
    String opc;
    String consulta;
    /**
     * Creates new form Mostrar_Informe
     */
    public Mostrar_Informe() {
        initComponents();
        modelo=cIc.mostrar(modelo);
        list_Informes.setModel(modelo);
        list_Informes.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        list_Informes.addListSelectionListener(new ListSelectionListener() {
            public void valueChanged(ListSelectionEvent e) {
                if (!e.getValueIsAdjusting()) {
                    String itemSeleccionado = list_Informes.getSelectedValue();
                    String[] separado=itemSeleccionado.split("-");
                    //JOptionPane.showMessageDialog(null, "Seleccionaste: " + separado[1]);
                    int id=Integer.parseInt(separado[0]);
                    cIc.Mos_Informe(id);

                    
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        list_Informes = new javax.swing.JList<>();
        btn_crearInforme = new javax.swing.JButton();
        ComboBox_Ordenar = new javax.swing.JComboBox<>();
        btn_Volver = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        list_Informes.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(list_Informes);

        btn_crearInforme.setText("Crear informe");
        btn_crearInforme.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_crearInformeActionPerformed(evt);
            }
        });

        ComboBox_Ordenar.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Mas reciente", "Mas antiguo" }));
        ComboBox_Ordenar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComboBox_OrdenarActionPerformed(evt);
            }
        });

        btn_Volver.setText("<--");
        btn_Volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_VolverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(86, 86, 86)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 84, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btn_crearInforme, javax.swing.GroupLayout.DEFAULT_SIZE, 117, Short.MAX_VALUE)
                    .addComponent(ComboBox_Ordenar, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(78, 78, 78))
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_Volver)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(btn_Volver)
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btn_crearInforme)
                        .addGap(29, 29, 29)
                        .addComponent(ComboBox_Ordenar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(111, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_crearInformeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_crearInformeActionPerformed
        Crear_Informe cI=new Crear_Informe();
        cI.setVisible(true);
        cI.setLocationRelativeTo(null);
        this.setVisible(false);
        cI.setSize(500,500);
    }//GEN-LAST:event_btn_crearInformeActionPerformed

    private void ComboBox_OrdenarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComboBox_OrdenarActionPerformed
        opc=ComboBox_Ordenar.getSelectedItem().toString();
        if (opc=="Mas reciente"){
            consulta = "SELECT ID, Titulo FROM Informe ORDER BY Fecha DESC";
        }else{
            consulta = "SELECT ID, Titulo FROM Informe ORDER BY Fecha ASC";
        }
        cIc.mostrar_Ordenado(modelo, consulta);
    }//GEN-LAST:event_ComboBox_OrdenarActionPerformed

    private void btn_VolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_VolverActionPerformed
        Pantalla_Seguridad pM = new Pantalla_Seguridad();
        pM.setVisible(true);
        this.setVisible(false);
        pM.setSize(1530,900);
        pM.setLocationRelativeTo(null);
    }//GEN-LAST:event_btn_VolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Mostrar_Informe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Mostrar_Informe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> ComboBox_Ordenar;
    private javax.swing.JButton btn_Volver;
    private javax.swing.JButton btn_crearInforme;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JList<String> list_Informes;
    // End of variables declaration//GEN-END:variables
}
