/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Entradas;
/**
 *
 * @author Agustín Salinas
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
        this.eventos.setSelected(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cerrar = new rsbuttom.RSButtonMetro();
        eventos = new rsbuttom.RSButtonMetro();
        notificaciones = new rsbuttom.RSButtonMetro();
        grupo = new rsbuttom.RSButtonMetro();
        historial = new rsbuttom.RSButtonMetro();
        panelPrincipal = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(31, 50, 69));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("ENTRADAS");

        cerrar.setBackground(new java.awt.Color(255, 255, 255));
        cerrar.setForeground(new java.awt.Color(31, 50, 69));
        cerrar.setText("HOME");
        cerrar.setColorHover(new java.awt.Color(255, 255, 255));
        cerrar.setColorNormal(new java.awt.Color(255, 255, 255));
        cerrar.setColorPressed(new java.awt.Color(38, 86, 186));
        cerrar.setColorTextHover(new java.awt.Color(31, 50, 69));
        cerrar.setColorTextNormal(new java.awt.Color(31, 50, 69));
        cerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cerrarMouseClicked(evt);
            }
        });

        eventos.setBackground(new java.awt.Color(31, 50, 69));
        eventos.setText("Eventos");
        eventos.setColorHover(new java.awt.Color(47, 94, 141));
        eventos.setColorNormal(new java.awt.Color(31, 50, 69));
        eventos.setColorPressed(new java.awt.Color(229, 232, 236));
        eventos.setColorTextPressed(new java.awt.Color(31, 50, 69));
        eventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                eventosMousePressed(evt);
            }
        });
        eventos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                eventosActionPerformed(evt);
            }
        });

        notificaciones.setBackground(new java.awt.Color(31, 50, 69));
        notificaciones.setIcon(new javax.swing.ImageIcon("C:\\Users\\Agustín Salinas\\Downloads\\klipartz.com.png")); // NOI18N
        notificaciones.setText("    Notificaciones");
        notificaciones.setBorderPainted(false);
        notificaciones.setColorHover(new java.awt.Color(47, 94, 141));
        notificaciones.setColorNormal(new java.awt.Color(31, 50, 69));
        notificaciones.setColorPressed(new java.awt.Color(229, 232, 236));
        notificaciones.setColorTextPressed(new java.awt.Color(31, 50, 69));
        notificaciones.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                notificacionesMousePressed(evt);
            }
        });
        notificaciones.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                notificacionesActionPerformed(evt);
            }
        });

        grupo.setBackground(new java.awt.Color(31, 50, 69));
        grupo.setIcon(new javax.swing.ImageIcon("C:\\Users\\Agustín Salinas\\Downloads\\klipartz.com.png")); // NOI18N
        grupo.setText("     Mi Grupo         ");
        grupo.setColorHover(new java.awt.Color(47, 94, 141));
        grupo.setColorNormal(new java.awt.Color(31, 50, 69));
        grupo.setColorPressed(new java.awt.Color(229, 232, 236));
        grupo.setColorTextPressed(new java.awt.Color(31, 50, 69));
        grupo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                grupoMousePressed(evt);
            }
        });
        grupo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                grupoActionPerformed(evt);
            }
        });

        historial.setBackground(new java.awt.Color(31, 50, 69));
        historial.setIcon(new javax.swing.ImageIcon("C:\\Users\\Agustín Salinas\\Downloads\\klipartz.com.png")); // NOI18N
        historial.setText("     Historial         ");
        historial.setColorHover(new java.awt.Color(47, 94, 141));
        historial.setColorNormal(new java.awt.Color(31, 50, 69));
        historial.setColorPressed(new java.awt.Color(229, 232, 236));
        historial.setColorTextPressed(new java.awt.Color(31, 50, 69));
        historial.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                historialMousePressed(evt);
            }
        });
        historial.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historialActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(eventos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(notificaciones, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(cerrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(grupo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addContainerGap(92, Short.MAX_VALUE))
            .addComponent(historial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(cerrar, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(25, 25, 25)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(eventos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(notificaciones, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(grupo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(historial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(233, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 520));

        panelPrincipal.setBackground(new java.awt.Color(229, 232, 236));
        panelPrincipal.setLayout(new javax.swing.BoxLayout(panelPrincipal, javax.swing.BoxLayout.LINE_AXIS));
        jPanel1.add(panelPrincipal, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 0, 700, 520));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 524, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void notificacionesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_notificacionesActionPerformed
        new CambiaPanel(panelPrincipal, new panelNotificaciones());
    }//GEN-LAST:event_notificacionesActionPerformed

    private void grupoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_grupoActionPerformed
        new CambiaPanel(panelPrincipal, new panelGrupo());
    }//GEN-LAST:event_grupoActionPerformed

    private void historialActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historialActionPerformed
        new CambiaPanel(panelPrincipal, new panelHistorial());
    }//GEN-LAST:event_historialActionPerformed

    private void eventosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_eventosActionPerformed
        // TODO add your handling code here:
        new CambiaPanel(panelPrincipal, new panelEventos());
        /*if(this.eventos.isSelected()){
            this.eventos.setColorNormal(new java.awt.Color(229,232,236));
            this.eventos.setColorTextNormal(new java.awt.Color(31,50,69));
            this.eventos.setEnabled(false);
            
            this.notificaciones.setColorNormal(new java.awt.Color(31,50,69));
            this.eventos.setColorTextNormal(new java.awt.Color(255,255,255));
            this.historial.setColorNormal(new java.awt.Color(31,50,69));
            this.eventos.setColorTextNormal(new java.awt.Color(255,255,255));
            this.grupo.setColorNormal(new java.awt.Color(31,50,69));
            this.eventos.setColorTextNormal(new java.awt.Color(255,255,255));
        }*/
    }//GEN-LAST:event_eventosActionPerformed

    private void eventosMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eventosMousePressed
        this.eventos.setSelected(true);
        this.notificaciones.setSelected(false);
        this.grupo.setSelected(false);
        this.historial.setSelected(false);
        
    }//GEN-LAST:event_eventosMousePressed

    private void notificacionesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_notificacionesMousePressed
        this.eventos.setSelected(false);
        this.notificaciones.setSelected(true);
        this.grupo.setSelected(false);
        this.historial.setSelected(false);
    }//GEN-LAST:event_notificacionesMousePressed

    private void grupoMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grupoMousePressed
        this.grupo.setSelected(true);
        this.notificaciones.setSelected(false);
        this.eventos.setSelected(false);
        this.historial.setSelected(false);
    }//GEN-LAST:event_grupoMousePressed

    private void historialMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historialMousePressed
        this.historial.setSelected(true);
        this.notificaciones.setSelected(false);
        this.grupo.setSelected(false);
        this.eventos.setSelected(false);
    }//GEN-LAST:event_historialMousePressed

    private void cerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cerrarMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_cerrarMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private rsbuttom.RSButtonMetro cerrar;
    private rsbuttom.RSButtonMetro eventos;
    private rsbuttom.RSButtonMetro grupo;
    private rsbuttom.RSButtonMetro historial;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private rsbuttom.RSButtonMetro notificaciones;
    private javax.swing.JPanel panelPrincipal;
    // End of variables declaration//GEN-END:variables
}
