/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Modulo_Ventas.Usuario;
import Modulo_Ventas.Usuario.Ingreso_Usuario;
import Modulo_Ventas.Pantalla_Ventas;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import Modulo_Ventas.ConexionBDD;
import java.util.logging.Logger;
import java.util.logging.Level;

/**
 *
 * @author thiag
 */
public class Gestion_Compra_Usuario extends javax.swing.JFrame {
    private String usuarioID; // Variable para almacenar el ID del usuario
    private String productoID;
    private int cantidadSeleccionada; // Variable para almacenar la cantidad seleccionada
    private static final Logger logger = Logger.getLogger(Gestion_Compra_Usuario.class.getName());
    /**
     * Creates new form Gestion_Compra_Reembolso_Usuario
     */
    public Gestion_Compra_Usuario(String usuarioID) {
        this.usuarioID = usuarioID;
        initComponents();
        datechooser_Fecha.setDate(new java.util.Date()); 
        datechooser_Fecha.setVisible(false); 
        Btn_ID.setVisible(false); 
        Btn_Nombre.setEnabled(false);
        Btn_Categoria.setEnabled(false);
        Btn_Precio.setEnabled(false);
        Compra_Usuario compra_usuario = new Compra_Usuario(); // Inicializar compra_usuario
        compra_usuario.MostrarProductos(TablaProductos); // Mostrar productos   
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        VolverPantalla = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        Btn_Nombre = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Btn_Categoria = new javax.swing.JTextField();
        Btn_ID = new javax.swing.JTextField();
        datechooser_Fecha = new com.toedter.calendar.JDateChooser();
        jLabel3 = new javax.swing.JLabel();
        Btn_Precio = new javax.swing.JTextField();
        Btn_Comprar = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        JTextField_Cantidad = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaProductos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        VolverPantalla.setText("<--");
        VolverPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                VolverPantallaActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Datos de Compra"));

        jLabel1.setText("Nombre");

        jLabel2.setText("Categoria");

        jLabel3.setText("Precio");

        Btn_Comprar.setText("Comprar");
        Btn_Comprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Btn_ComprarActionPerformed(evt);
            }
        });

        jLabel4.setText("Cantidad");

        JTextField_Cantidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JTextField_CantidadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_Nombre, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Categoria, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Precio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Btn_Comprar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(Btn_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(36, 36, 36)
                                .addComponent(jLabel1))
                            .addComponent(datechooser_Fecha, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(55, 55, 55)
                                .addComponent(jLabel3))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel2))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(50, 50, 50)
                                .addComponent(jLabel4))
                            .addComponent(JTextField_Cantidad))
                        .addGap(0, 10, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Btn_ID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Btn_Categoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(JTextField_Cantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(datechooser_Fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Btn_Comprar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        TablaProductos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        TablaProductos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TablaProductosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(TablaProductos);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 342, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(VolverPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(VolverPantalla)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(37, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void VolverPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_VolverPantallaActionPerformed
        Menu_Usuario mU= new Menu_Usuario(usuarioID);
        this.setVisible(false);
        mU.setSize(500,500);
        mU.setLocationRelativeTo(null);
        mU.setVisible(true);
    }//GEN-LAST:event_VolverPantallaActionPerformed

    private void TablaProductosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TablaProductosMouseClicked
    int filaSeleccionada = TablaProductos.getSelectedRow();
        if (filaSeleccionada != -1) {
            // Obtiene el ProductoID de la fila seleccionada
            productoID = TablaProductos.getValueAt(filaSeleccionada, 0).toString();
            
            // Establece la fecha actual
            datechooser_Fecha.setDate(new java.util.Date());

            // Llama a SeleccionarProducto y pasa los JTextField
            Compra_Usuario objetoUsuario = new Compra_Usuario();
            objetoUsuario.SeleccionarProducto(TablaProductos, Btn_ID, Btn_Nombre, Btn_Precio, Btn_Categoria);
        }
        
    }//GEN-LAST:event_TablaProductosMouseClicked

    private void Btn_ComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Btn_ComprarActionPerformed
     System.out.println("Iniciando Btn_ComprarActionPerformed...");

    // Verifica que se haya seleccionado un producto
    if (productoID != null && !productoID.isEmpty()) {
        // Obtén el texto del JTextField y conviértelo a un número
        String cantidadTexto = JTextField_Cantidad.getText();
        int cantidadSeleccionada = 0; // Cambia a 0 o a una cantidad predeterminada

        try {
            cantidadSeleccionada = Integer.parseInt(cantidadTexto); // Intenta convertir el texto a un entero
            System.out.println("Cantidad seleccionada: " + cantidadSeleccionada);

            if (cantidadSeleccionada <= 0) {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona una cantidad válida antes de continuar.");
                return;
            }

            // Verificar stock disponible
            Compra_Usuario compraUsuario = new Compra_Usuario();
            int idProducto = Integer.parseInt(productoID);
            int stockDisponible = compraUsuario.obtenerStockProducto(idProducto);
            System.out.println("Stock disponible: " + stockDisponible);

            if (cantidadSeleccionada > stockDisponible) {
                JOptionPane.showMessageDialog(this, "No hay suficiente stock disponible. Stock actual: " + stockDisponible, "Error", JOptionPane.ERROR_MESSAGE);
                return; // Salimos si no hay suficiente stock
            }

            // Verifica que se haya seleccionado una fecha
            if (datechooser_Fecha.getDate() != null) {
                // Formatear la fecha a un string usando la fecha seleccionada
                SimpleDateFormat formatoFecha = new SimpleDateFormat("yyyy-MM-dd");
                String fechaString = formatoFecha.format(datechooser_Fecha.getDate());

                // Crear la siguiente ventana, pasando los datos necesarios
                Gestion_CompraTarjeta_Usuario ventanaCompra = new Gestion_CompraTarjeta_Usuario(usuarioID, productoID, fechaString, cantidadSeleccionada);

                // Configura y muestra la nueva ventana
                ventanaCompra.setSize(500, 500);
                ventanaCompra.setLocationRelativeTo(null);
                ventanaCompra.setVisible(true);

                // Oculta la ventana actual
                this.setVisible(false);
            } else {
                JOptionPane.showMessageDialog(this, "Por favor, selecciona una fecha para la compra.");
            }
        } catch (NumberFormatException e) {
            // Manejo de error si la conversión falla
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una cantidad válida.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    } else {
        // Mensaje de error si no hay producto seleccionado
        JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para comprar.");
    }

    System.out.println("Finalizando Btn_ComprarActionPerformed.");


    
// TODO add your handling code here:
    }//GEN-LAST:event_Btn_ComprarActionPerformed

    private void JTextField_CantidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JTextField_CantidadActionPerformed
    System.out.println("Iniciando Btn_CantidadActionPerformed...");

    String cantidadTexto = JTextField_Cantidad.getText(); // Obtén el texto del JTextField
    System.out.println("Texto ingresado en Btn_Cantidad: " + cantidadTexto);
    int cantidad;

    try {
        cantidad = Integer.parseInt(cantidadTexto);
        System.out.println("Cantidad convertida a int: " + cantidad);

        if (cantidad <= 0) {
            JOptionPane.showMessageDialog(this, "Por favor, ingresa una cantidad válida mayor que 0.", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("Cantidad ingresada no válida (menor o igual a 0).");
            return;
        }

        if (productoID != null && !productoID.isEmpty()) {
            Compra_Usuario compraUsuario = new Compra_Usuario();
            int idProducto = Integer.parseInt(productoID);
            int stockDisponible = compraUsuario.obtenerStockProducto(idProducto);
            System.out.println("Stock disponible: " + stockDisponible);

            if (cantidad > stockDisponible) {
                JOptionPane.showMessageDialog(this, "No hay suficiente stock disponible. Stock actual: " + stockDisponible, "Error", JOptionPane.ERROR_MESSAGE);
                System.out.println("Cantidad ingresada mayor que el stock disponible.");
                return;
            } else {
                cantidadSeleccionada = cantidad; // Asignar cantidad seleccionada
                System.out.println("Cantidad seleccionada correctamente: " + cantidadSeleccionada);
                JOptionPane.showMessageDialog(this, "Cantidad seleccionada: " + cantidadSeleccionada);
                
                // Aquí puedes habilitar el botón de compra si lo has deshabilitado
                Btn_Comprar.setEnabled(true); // Habilita el botón de compra
            }
        } else {
            JOptionPane.showMessageDialog(this, "Por favor, selecciona un producto para verificar el stock.", "Error", JOptionPane.ERROR_MESSAGE);
            System.out.println("No se ha seleccionado un producto.");
        }
    } catch (NumberFormatException e) {
        JOptionPane.showMessageDialog(this, "Por favor, ingresa solo números.", "Error", JOptionPane.ERROR_MESSAGE);
        System.out.println("Error: entrada no numérica.");
    }

    System.out.println("Finalizando Btn_CantidadActionPerformed.");
// TODO add your handling code here:
    }//GEN-LAST:event_JTextField_CantidadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Gestion_Compra_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Gestion_Compra_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Gestion_Compra_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Gestion_Compra_Usuario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Btn_Categoria;
    private javax.swing.JButton Btn_Comprar;
    private javax.swing.JTextField Btn_ID;
    private javax.swing.JTextField Btn_Nombre;
    private javax.swing.JTextField Btn_Precio;
    private javax.swing.JTextField JTextField_Cantidad;
    private javax.swing.JTable TablaProductos;
    private javax.swing.JButton VolverPantalla;
    private com.toedter.calendar.JDateChooser datechooser_Fecha;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
